# backend:
#   name: git-gateway
#   branch: main

backend:
  name: test-repo

media_folder: site/static/img
public_folder: img

show_preview_links: false

collections:
  - name: event
    editor:
      preview: false
    label: Event
    folder: site/content/event
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Start Date, name: date, widget: datetime}
      - {label: End Date, name: end, widget: datetime}
      - {label: All Day, name: allDay, widget: boolean}
      - {label: Description, name: description, widget: text}
      - {label: Venue, name: venue, widget: text}
      - {label: Link, name: link, widget: string, required: false}
      - {label: Image, name: image, widget: image, required: false}
  - name: site_settings
    label: Site Settings
    files:
      - file: site/config.toml
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
