backend:
  name: git-gateway
  branch: main

# backend:
#   name: test-repo

media_folder: site/static/img
public_folder: img

show_preview_links: false

collections:
  - name: event
    editor:
      preview: false
    label: Event
    folder: site/content/event
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Start Date, name: date, widget: datetime}
      - {label: End Date, name: end, widget: datetime, required: false}
      - {label: All Day, name: allDay, widget: boolean, required: false}
      - {label: Description, name: description, widget: text}
      - {label: Flyer, name: flyer, widget: image, required: false}
